console.log('test isVowel function')
console.log('test a single string of a: ')
console.log(isVowel('a'))
console.log('test a string of bbaa: ')
console.log(isVowel('bbaa'))
console.log('test the number 2: ')
console.log(isVowel(2))

console.log('test countVowels function')
console.log('testing the string of letters asdsdgoek :')
console.log(countVowels('asdsdgoek'))
console.log('testing the string of letters abcdefghijklmnopqrstuvwxyz :')
console.log(countVowels('abcdefghijklmnopqrstuvwxyz'))
console.log('testing the string of letters aeiou :')
console.log(countVowels('aeiou'))
console.log('testing the string of letters aaaaaaaaaaa :')
console.log(countVowels('aaaaaaaaaaa'))